repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.19.0
    hooks:
      - id: slotscheck
        exclude: test_*|docs|migrations|scripts
        entry: env PYTHONPATH=src slotscheck
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        exclude: scripts/
        additional_dependencies:
          - passlib[argon2]
          - asyncpg
          - asyncpg-stubs
          - litestar[jinja,jwt,redis,structlog]
          - "advanced-alchemy[uuid]"
          - litestar-granian
          - litestar-saq
          - types-python-jose
          - types-click
          - types-redis
          - types-passlib
          - types-click
          - types-PyYAML
